#+TITLE: jupyter layer

* Table of Contents                                        :TOC_1_gh:noexport:
- [[#description][Description]]
- [[#install][Install]]
- [[#key-bindings][Key bindings]]

* Description
  A spacemacs layer for Jupyter REPLs and their integration with =org-mode=,
  including integration with =org-babel= and exporting of =org= files to
  =.ipynb=. Currently a fork of [[https://github.com/benneti/spacemacs-jupyter][benneti's jupyter layer]], though I have not
  decided if I wish to keep this as a personal private layer.

** Features
   Includes the following packages:
   - [[https://github.com/dzop/emacs-jupyter][dzop's =emacs-jupyter=]]
   - [[https://github.com/jkitchin/ox-ipynb][jkitchin's =ox-ipynb=]]
   - =company= via the =company-capf= backend

* Install
  To use this configuration layer, add it to your =~/.spacemacs=. You will need to
  add =jupyter= to the existing =dotspacemacs-configuration-layers= list in this
  file.

  Additionally you need to have =jupyter= available in your =PATH=.

  The jupyter package also provides integration with =org-babel= via =ob-jupyter=.
  To use the kernels in jupyter just add =(jupyter . t)= to your
  =org-babel-load-languages= list as the last element.
  If no auto-completion is used adding to the variable is sufficient as spacemacs
  provides a hook that loads it the first time =org-mode= is started.

  An example would be adding

  #+BEGIN_SRC emacs-lisp
  (with-eval-after-load 'org
    (setq org-babel-load-languages
          (append org-babel-load-languages
                  '((latex . t)
                    ;; jupyter has to be the last element
                    (jupyter . t))))
    ;; Execute load languages once, else autocompletion will only work in the
    ;; second org file one opens
    (spacemacs//org-babel-do-load-languages))
  #+END_SRC

  to your =dotspacemacs/user-config=.

* Key bindings
  As of this upload, I have removed all key bindings except for the following.

  | Key Binding | Description     |
  |-------------+-----------------|
  | ~SPC a j j~ | Start new REPL  |
  | ~SPC a j r~ | Start new REPL  |
  | ~SPC a j c~ | Connect to REPL |

# Use GitHub URLs if you wish to link a Spacemacs documentation file or its heading.
# Examples:
# [[https://github.com/syl20bnr/spacemacs/blob/master/doc/VIMUSERS.org#sessions]]
# [[https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bfun/emoji/README.org][Link to Emoji layer README.org]]
# If space-doc-mode is enabled, Spacemacs will open a local copy of the linked file.
